# The URL the site will be built for
title = "ludihan"
description = "ludihan's personal website"
base_url = "https://ludihan.xyz"
minify_html = true
compile_sass = true
build_search_index = true

[markdown]

[markdown.highlighting]
theme = "gruvbox-dark-medium"

[extra]
# Put all your custom variables here
